#!/usr/bin/env python3
"""Generic config projector.

Reads the user's canonical settings.json + mcp.json and writes ONE harness's
config in whatever format that harness wants. It has no knowledge of any
specific harness -- everything it does is driven by flags the plugin supplied
(--format, --mcp-key, --map, --preserve).

Canonical settings.json shape:

    {
      "common":  { ... knobs shared across harnesses, projected via --map ... },
      "harness": { "<name>": { ... raw passthrough for that harness only ... } }
    }
"""
from __future__ import annotations

import argparse, json, os, re, sys

try:
    import tomllib
except ModuleNotFoundError:
    tomllib = None


# --- helpers ------------------------------------------------------------------

def load_secrets(path):
    """KEY=value lines. Never committed; referenced as ${KEY} in the canon."""
    if not path or not os.path.exists(path):
        return
    for line in open(path, encoding="utf-8"):
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        k, v = line.split("=", 1)
        os.environ.setdefault(k.strip(), v.strip().strip("'\""))


def expand(obj):
    """Resolve ${VAR} and $HOME anywhere in the tree. Missing var -> empty."""
    if isinstance(obj, str):
        s = re.sub(r"\$\{([A-Za-z_][A-Za-z0-9_]*)\}",
                   lambda m: os.environ.get(m.group(1), ""), obj)
        return s.replace("$HOME", os.path.expanduser("~"))
    if isinstance(obj, dict):
        return {k: expand(v) for k, v in obj.items()}
    if isinstance(obj, list):
        return [expand(v) for v in obj]
    return obj


def dset(d, dotted, value):
    """Set a dotted key path, creating intermediate dicts."""
    parts = dotted.split(".")
    for p in parts[:-1]:
        d = d.setdefault(p, {})
    d[parts[-1]] = value


def dget(d, dotted, default=None):
    for p in dotted.split("."):
        if not isinstance(d, dict) or p not in d:
            return default
        d = d[p]
    return d


def visible(entry, profile):
    profs = entry.get("profiles", ["common"]) if isinstance(entry, dict) else ["common"]
    return any(p in ("common", "all", profile) for p in profs)


# --- format writers -----------------------------------------------------------

BANNER = ("GENERATED by tack. Edit your canonical settings.json / mcp.json "
          "instead -- changes here are overwritten.")


def to_json(data, banner_key="_generated"):
    out = dict(data)
    out[banner_key] = BANNER
    return json.dumps(out, indent=2) + "\n"


def to_jsonc(data):
    return f"// {BANNER}\n" + json.dumps(data, indent=2) + "\n"


def toml_value(v):
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, (int, float)):
        return json.dumps(v)
    if isinstance(v, str):
        return json.dumps(v)
    if isinstance(v, list):
        return "[" + ", ".join(toml_value(x) for x in v) + "]"
    raise TypeError(f"cannot express in TOML: {v!r}")


def toml_key(k):
    return k if re.fullmatch(r"[A-Za-z0-9_-]+", k) else json.dumps(k)


def to_toml(data):
    lines = [f"# {BANNER}", ""]

    def emit(d, prefix=""):
        scalars = {k: v for k, v in d.items() if not isinstance(v, dict)}
        tables = {k: v for k, v in d.items() if isinstance(v, dict)}
        for k, v in scalars.items():
            lines.append(f"{toml_key(k)} = {toml_value(v)}")
        if scalars:
            lines.append("")
        for k, v in tables.items():
            name = f"{prefix}{toml_key(k)}"
            lines.append(f"[{name}]")
            emit(v, name + ".")
            if lines[-1] != "":
                lines.append("")

    emit(data)
    return "\n".join(lines).rstrip() + "\n"


def to_yaml(data):
    try:
        import yaml
    except ModuleNotFoundError:
        sys.exit("render: yaml format needs PyYAML installed")
    return f"# {BANNER}\n" + yaml.safe_dump(data, sort_keys=False)


def read_existing(path, fmt):
    """Parse whatever is already at path, so --preserve can carry keys through."""
    if not os.path.exists(path):
        return {}
    raw = open(path, "rb").read()
    try:
        if fmt == "toml":
            return tomllib.loads(raw.decode()) if tomllib else {}
        text = raw.decode()
        if fmt == "jsonc":
            text = re.sub(r"^\s*//.*$", "", text, flags=re.M)
        return json.loads(text or "{}")
    except Exception:
        return {}


# --- main ---------------------------------------------------------------------

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--settings", required=True)
    ap.add_argument("--mcp")
    ap.add_argument("--profile", default="personal")
    ap.add_argument("--harness", required=True)
    ap.add_argument("--out", required=True)
    ap.add_argument("--format", default="json", choices=["json", "jsonc", "toml", "yaml"])
    ap.add_argument("--mcp-key")
    ap.add_argument("--map", action="append", default=[],
                    help='"common_key|dotted.dest.path"')
    ap.add_argument("--preserve", action="append", default=[],
                    help="top-level key the harness writes itself; carried through")
    ap.add_argument("--secrets")
    args = ap.parse_args()

    load_secrets(args.secrets)

    canon = {}
    if os.path.exists(args.settings):
        canon = expand(json.load(open(args.settings, encoding="utf-8")))
    common = canon.get("common", {})

    # 1. raw passthrough for this harness
    data = dict(canon.get("harness", {}).get(args.harness, {}))

    # 2. shared knobs, projected where the plugin said they go
    for m in args.map:
        src, _, dest = m.partition("|")
        val = dget(common, src)
        if val is not None:
            dset(data, dest or src, val)

    # 3. MCP registry, filtered by profile, under the key the plugin named
    if args.mcp_key and args.mcp and os.path.exists(args.mcp):
        servers = expand(json.load(open(args.mcp, encoding="utf-8")))
        servers = {k: {kk: vv for kk, vv in v.items() if kk != "profiles"}
                   for k, v in servers.items()
                   if not k.startswith("_") and isinstance(v, dict) and visible(v, args.profile)}
        if servers:
            dset(data, args.mcp_key, servers)

    # 4. keys the harness owns and writes back into its own config
    existing = read_existing(args.out, args.format)
    for k in args.preserve:
        if k in existing:
            data[k] = existing[k]

    text = {"json": to_json, "jsonc": to_jsonc, "toml": to_toml, "yaml": to_yaml}[args.format](data)

    if os.path.exists(args.out) and open(args.out, encoding="utf-8").read() == text:
        return
    if os.environ.get("TACK_DRY") == "1":
        print(f"  \033[33mwould render\033[0m {args.out}")
        return

    os.makedirs(os.path.dirname(args.out) or ".", exist_ok=True)
    if os.path.exists(args.out):
        prev = open(args.out, encoding="utf-8", errors="replace").read()
        if "GENERATED by tack" not in prev:
            bak = args.out + ".pre-tack.bak"
            open(bak, "w", encoding="utf-8").write(prev)
            print(f"  \033[33mbackup\033[0m {bak}")
    open(args.out, "w", encoding="utf-8").write(text)
    print(f"  \033[32mrender\033[0m {args.out}")


if __name__ == "__main__":
    main()
